service: change-calculator

package:
  exclude:
    - client/**
    - test/**
    - README.md
    - package-lock.json

provider:
  name: aws
  runtime: nodejs6.10
  stage: production
  region: eu-west-1

plugins:
  - serverless-offline

functions:
  app:
    handler: handler.handler
    events:
      - http: 'ANY {proxy+}'

resources:  # CloudFormation template syntax
  Resources:
    CDN:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          ViewerCertificate:
            CloudFrontDefaultCertificate: true
          Enabled: true
          HttpVersion: http2
          Aliases: [changecalc.leonyork.com]
          Origins:
            - DomainName: {"Fn::Join": ["", [{"Ref": "ApiGatewayRestApi"}, ".execute-api.${self:provider.region}.amazonaws.com"]]}
              Id: Serverless-origin
              OriginPath: "/${self:provider.stage}"
              CustomOriginConfig:
                HTTPSPort: 443
                OriginProtocolPolicy: https-only
          PriceClass: PriceClass_100
          DefaultCacheBehavior:
            ViewerProtocolPolicy: allow-all
            TargetOriginId: Serverless-origin
            AllowedMethods:
              - GET
              - HEAD
            Compress: true
            DefaultTTL: 30
            MinTTL: 10
            ForwardedValues:
              QueryString: true