service: change-calculator

provider:
  name: aws
  runtime: nodejs6.10
  stage: production
  region: eu-west-1

plugins:
  - serverless-offline

functions:
  app:
    handler: handler.handler
    events:
      - http: 'ANY {proxy+}'