service: change-calculator

provider:
  name: aws
  runtime: nodejs6.10
  stage: production
  region: eu-west-1

plugins:
  - serverless-offline
  - serverless-api-cloudfront

functions:
  app:
    handler: handler.handler
    events:
      - http: 'ANY {proxy+}'

custom:
  apiCloudFront:
    domain: changecalc.leonyork.com
    headers: all
    querystring: all